### ISSUE TITLE
Live demo with Realsense

### ISSUE THREAD

**Issue by Tanfuchy** [muskie82/MonoGS#116]
(MonoGS)$ python slam.py --config configs/live/realsense_rgbd.yaml
Traceback (most recent call last):
  File "slam.py", line 252, in <module>
    slam = SLAM(config, save_dir=save_dir)
  File "slam.py", line 56, in __init__
    model_params, model_params.source_path, config=config
  File "/home/chy/mycode/MonoGS/utils/dataset.py", line 530, in load_dataset
    return RealsenseDataset(args, path, config)
  File "/home/chy/mycode/MonoGS/utils/dataset.py", line 432, in __init__
    self.pipeline = rs.pipeline()
NameError: name 'rs' is not defined

 python slam.py --config configs/live/realsense.yaml
Traceback (most recent call last):
  File "slam.py", line 252, in <module>
    slam = SLAM(config, save_dir=save_dir)
  File "slam.py", line 56, in __init__
    model_params, model_params.source_path, config=config
  File "/home/chy/mycode/MonoGS/utils/dataset.py", line 530, in load_dataset
    return RealsenseDataset(args, path, config)
  File "/home/chy/mycode/MonoGS/utils/dataset.py", line 432, in __init__
    self.pipeline = rs.pipeline()
NameError: name 'rs' is not defined

**Comment by harshal-14** [comment]
I guess you are missing the pyrealsense library installation. Ensure you have that installed in your environment:
https://pypi.org/project/pyrealsense2/

Make sure you import it at the top of the file.

**Comment by MikeAiJF** [comment]
![image](https://github.com/user-attachments/assets/63835e2d-6598-4b8d-8e63-45f1ce4892a1)
How should this error be resolved

**Comment by MutimirStajdohar** [comment]
Follow this:
https://github.com/IntelRealSense/librealsense/blob/development/doc/distribution_linux.md
If you manage to see it using the realsense-viewer you should not get this error.
