### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'projmatrix_raw'

### ISSUE THREAD

**Issue by Niamh5163** [muskie82/MonoGS#124]
Hi, I have the following problem when trying to run the command python slam.py --config configs/mono/tum/fr1_desk.yaml and would like to ask how to fix it? Thank you very much for your help!
`MonoGS: saving results in 
results/tum_rgbd_dataset_freiburg1_desk/2024-08-08-10-20-57
FEngine (64 bits) created at 0x39f69f90 (threading is enabled)
FEngine resolved backend: OpenGL
MonoGS: Resetting the system
Process Process-3:
Traceback (most recent call last):
  File "/home/yjj/anaconda3/envs/MonoGS/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/yjj/anaconda3/envs/MonoGS/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yjj/MonoGS/utils/slam_backend.py", line 406, in run
    self.initialize_map(cur_frame_idx, viewpoint)
  File "/home/yjj/MonoGS/utils/slam_backend.py", line 90, in initialize_map
    viewpoint, self.gaussians, self.pipeline_params, self.background
  File "/home/yjj/MonoGS/gaussian_splatting/gaussian_renderer/__init__.py", line 71, in render
    debug=False,
TypeError: __new__() got an unexpected keyword argument 'projmatrix_raw'
`

**Comment by Niamh5163** [comment]
To add, my experimental environment is ubuntu20.04, and the environment.yml is configured as follows：
name: MonoGS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - submodules/simple-knn
    - submodules/diff-gaussian-rasterization
    - opencv-python==4.8.1.78
    - munch
    - trimesh
    - evo==1.11.0
    - open3d==0.17.0
    - torchmetrics
    - imgviz
    - PyOpenGL
    - glfw
    - PyGLM
    - wandb
    - lpips
    - rich
    - ruff
 I'd appreciate it if you could solve my problem！

**Comment by Niamh5163** [comment]
I realised that someone else had already had this problem earlier. hhh
