### ISSUE TITLE
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`

### ISSUE THREAD

**Issue by zuoweic** [muskie82/MonoGS#132]
/home/y/anaconda3/envs/MonoGS/bin/python /home/y/4tdisk/MonoGS/slam.py --config configs/mono/tum/fr3_office.yaml 
MonoGS: saving results in results/datasets_tum/2024-08-15-10-44-40
FEngine (64 bits) created at 0x3667b4c0 (threading is enabled)
FEngine resolved backend: OpenGL
MonoGS: Resetting the system
Process Process-3:
Traceback (most recent call last):
  File "/home/y/anaconda3/envs/MonoGS/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/y/anaconda3/envs/MonoGS/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/y/4tdisk/MonoGS/utils/slam_backend.py", line 404, in run
    cur_frame_idx, viewpoint, depth_map=depth_map, init=True
  File "/home/y/4tdisk/MonoGS/utils/slam_backend.py", line 69, in add_next_kf
    viewpoint, kf_id=frame_idx, init=init, scale=scale, depthmap=depth_map
  File "/home/y/4tdisk/MonoGS/gaussian_splatting/scene/gaussian_model.py", line 239, in extend_from_pcd_seq
    self.create_pcd_from_image(cam_info, init, scale=scale, depthmap=depthmap)
  File "/home/y/4tdisk/MonoGS/gaussian_splatting/scene/gaussian_model.py", line 131, in create_pcd_from_image
    return self.create_pcd_from_image_and_depth(cam, rgb, depth, init)
  File "/home/y/4tdisk/MonoGS/gaussian_splatting/scene/gaussian_model.py", line 150, in create_pcd_from_image_and_depth
    W2C = getWorld2View2(cam.R, cam.T).cpu().numpy()
  File "/home/y/4tdisk/MonoGS/gaussian_splatting/utils/graphics_utils.py", line 41, in getWorld2View2
    C2W = torch.linalg.inv(Rt)
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`

need help........

**Comment by zuoweic** [comment]
restart................i solved it
