### ISSUE TITLE
About realsensed435i

### ISSUE THREAD

**Issue by ChaselLau666** [muskie82/MonoGS#39]
when i run python slam.py --config configs/live/realsense.yaml
Traceback (most recent call last):
  File "slam.py", line 252, in <module>
    slam = SLAM(config, save_dir=save_dir)
  File "slam.py", line 56, in __init__
    model_params, model_params.source_path, config=config
  File "/home/xiangchengliu/MonoGS/utils/dataset.py", line 496, in load_dataset
    return RealsenseDataset(args, path, config)
  File "/home/xiangchengliu/MonoGS/utils/dataset.py", line 434, in __init__
    self.profile = self.pipeline.start(self.config)
RuntimeError: Couldn't resolve requests

**Comment by muskie82** [comment]
Hi,
Seems like realsense is not opened.
Can you try some of the [pyrealsense example codes](https://github.com/IntelRealSense/librealsense/tree/master/wrappers/python/examples) and check if it works?
