### ISSUE TITLE
 CUDA error: the launch timed out and was terminated

### ISSUE THREAD

**Issue by foreverlong** [muskie82/MonoGS#47]
Thank you for this program! First,I appologize for my poor English. Sorry!
When I successfully build the environment, then I run it. But I meet these problem. At first, It can run some photo,Then it stuck.
![image](https://github.com/muskie82/MonoGS/assets/43675453/3a1adc06-3277-4ab2-98a9-8821ce6fb946)

`(MonoGS) PS D:\MonoGS> python .\slam.py --config .\configs\rgbd\tum\fr1_desk.yaml
MonoGS: saving results in results\datasets_tum\2024-04-01-13-12-54
FEngine (64 bits) created at 000002063B5DB050 (threading is enabled)
FEngine resolved backend: OpenGL
MonoGS: Resetting the system
MonoGS: Initialized map
Process Process-3:
Traceback (most recent call last):
  File "D:\Conda\envs\MonoGS\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\Conda\envs\MonoGS\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\MonoGS\utils\slam_backend.py", line 382, in run
    self.map(self.current_window, prune=True, iters=10)
  File "D:\MonoGS\utils\slam_backend.py", line 193, in map
    self.config, image, depth, viewpoint, opacity
  File "D:\MonoGS\utils\slam_utils.py", line 98, in get_loss_mapping
    return get_loss_mapping_rgbd(config, image_ab, depth, viewpoint)
  File "D:\MonoGS\utils\slam_utils.py", line 120, in get_loss_mapping_rgbd
    dtype=torch.float32, device=image.device
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File ".\slam.py", line 252, in <module>
    slam = SLAM(config, save_dir=save_dir)
  File ".\slam.py", line 110, in __init__
    self.frontend.run()
  File "D:\MonoGS\utils\slam_frontend.py", line 392, in run
    render_pkg = self.tracking(cur_frame_idx, viewpoint)
  File "D:\MonoGS\utils\slam_frontend.py", line 174, in tracking
    self.config, image, depth, opacity, viewpoint
  File "D:\MonoGS\utils\slam_utils.py", line 60, in get_loss_tracking
    return get_loss_tracking_rgbd(config, image_ab, depth, opacity, viewpoint)
  File "D:\MonoGS\utils\slam_utils.py", line 80, in get_loss_tracking_rgbd
    dtype=torch.float32, device=image.device
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.`

**Comment by rmurai0610** [comment]
It looks related to #36 #20, but we've not solved this problem yet (we don't have a Windows machine at hand)
If anyone finds a solution, please let us know!
