### ISSUE TITLE
May I ask how to solve this problem:TypeError: __new__() got an unexpected keyword argument 'projmatrix_raw'

### ISSUE THREAD

**Issue by Yuho994** [muskie82/MonoGS#74]
(MonoGS) E:\work\github\MonoGS>python slam.py --config configs/mono/tum/fr3_office.yaml
MonoGS: saving results in results\datasets_tum\2024-04-19-11-51-28
FEngine (64 bits) created at 000002A4A4ADA050 (threading is enabled)
FEngine resolved backend: OpenGL
MonoGS: Resetting the system
Process Process-3:
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\MonoGS\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\ProgramData\anaconda3\envs\MonoGS\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "E:\work\github\MonoGS\utils\slam_backend.py", line 406, in run
    self.initialize_map(cur_frame_idx, viewpoint)
  File "E:\work\github\MonoGS\utils\slam_backend.py", line 90, in initialize_map
    viewpoint, self.gaussians, self.pipeline_params, self.background
  File "E:\work\github\MonoGS\gaussian_splatting\gaussian_renderer\__init__.py", line 71, in render
    debug=False,
TypeError: __new__() got an unexpected keyword argument 'projmatrix_raw'

**Comment by muskie82** [comment]
Hi,
Checkout #9.

Best,
