### ISSUE TITLE
Building Error with simple_knn and diff_gaussian_rasterization

### ISSUE THREAD

**Issue by WeiguangHan** [muskie82/MonoGS#84]
I tried to set up the environment using the command `conda env create -f environment.yml`. But some errors occured. This is the log and setup of my machine. Thanks for your comments in advance!

Env:

- cuda 11.6
- gcc 9.4.0
- ubuntu 20.04

```
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Downloading wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
Building wheels for collected packages: evo, simple_knn, diff_gaussian_rasterization, imgviz, PyGLM
  Building wheel for evo (setup.py): started
  Building wheel for evo (setup.py): finished with status 'done'
  Created wheel for evo: filename=evo-1.11.0-py3-none-any.whl size=124672 sha256=6e0498bb116a539a724523fa8f6254ef433c418f06ebfacaef73c27172aabdda
  Stored in directory: /home/hwg/.cache/pip/wheels/1f/e3/f7/1147794e716c5e8bb112b893ab1a7d59f7cebefed0c28bd126
  Building wheel for simple_knn (setup.py): started
  Building wheel for simple_knn (setup.py): finished with status 'error'
  Running setup.py clean for simple_knn
  Building wheel for diff_gaussian_rasterization (setup.py): started
  Building wheel for diff_gaussian_rasterization (setup.py): finished with status 'error'
  Running setup.py clean for diff_gaussian_rasterization
  Building wheel for imgviz (setup.py): started
  Building wheel for imgviz (setup.py): finished with status 'done'
  Created wheel for imgviz: filename=imgviz-1.7.5-py3-none-any.whl size=7680233 sha256=2a8e73a059b654f35608128fa4d5fb830a738fbeb555186c3e43a2efe02d7f8a
  Stored in directory: /home/hwg/.cache/pip/wheels/88/94/9d/2b32018d3b7376911ce9789f4e8512b3668eab4325bf96a8b1
  Building wheel for PyGLM (setup.py): started
  Building wheel for PyGLM (setup.py): still running...
  Building wheel for PyGLM (setup.py): finished with status 'done'
  Created wheel for PyGLM: filename=PyGLM-2.7.1-cp37-cp37m-linux_x86_64.whl size=10625607 sha256=825cf0c51129a0d0de383f250538fe48e2396b7c9db82caa0d5b53f02d0e0534
  Stored in directory: /home/hwg/.cache/pip/wheels/4a/39/6c/99b2f2df313bf4cff85c11c5af3d8d036fb9b4c02f2f789d50
Successfully built evo imgviz PyGLM
Failed to build simple_knn diff_gaussian_rasterization
Installing collected packages: wcwidth, simple_knn, pytz, PyOpenGL, PyGLM, ptyprocess, pickleshare, glfw, fastjsonschema, diff_gaussian_rasterization, dash-table, dash-html-components, dash-core-components, backcall, appdirs, addict, zipp, widgetsnbextension, trimesh, traitlets, threadpoolctl, tenacity, smmap, setproctitle, sentry-sdk, scipy, ruff, retrying, pyyaml, python-dateutil, pyrsistent, pyquaternion, pyparsing, pygments, psutil, protobuf, prompt-toolkit, pkgutil-resolve-name, pillow, pexpect, parso, packaging, opencv-python, nest-asyncio, natsort, mdurl, MarkupSafe, kiwisolver, jupyterlab-widgets, joblib, itsdangerous, fonttools, docker-pycreds, decorator, cycler, configargparse, werkzeug, torchmetrics, scikit-learn, plotly, pandas, matplotlib-inline, matplotlib, markdown-it-py, jupyter-core, Jinja2, jedi, importlib-resources, importlib-metadata, gitdb, comm, seaborn, rich, munch, lpips, ipython, imgviz, GitPython, Click, attrs, argcomplete, wandb, jsonschema, ipywidgets, Flask, evo, nbformat, dash, open3d
  Running setup.py install for simple_knn: started
  Running setup.py install for simple_knn: finished with status 'error'
 
Pip subprocess error:
  error: subprocess-exited-with-error
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.7'
      running bdist_wheel
      /home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_ext
      /home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.7) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.7
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'simple_knn._C' extension
      creating build
      creating build/temp.linux-x86_64-cpython-37
      gcc -pthread -B /home/hwg/miniconda3/envs/MonoGS/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/include -I/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/include/TH -I/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/hwg/miniconda3/envs/MonoGS/include/python3.7m -c ext.cpp -o build/temp.linux-x86_64-cpython-37/ext.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
      cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/hwg/2_Code/MonoGS/submodules/simple-knn/setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/ccompiler.py", line 600, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 513, in unix_wrap_single_compile
          cflags = unix_cuda_flags(cflags)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 480, in unix_cuda_flags
          cflags + _get_cuda_arch_flags(cflags))
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1694, in _get_cuda_arch_flags
          arch_list[-1] += '+PTX'
      IndexError: list index out of range
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple_knn
  error: subprocess-exited-with-error
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.7'
      running bdist_wheel
      /home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-37
      creating build/lib.linux-x86_64-cpython-37/diff_gaussian_rasterization
      copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-37/diff_gaussian_rasterization
      running build_ext
      /home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.7) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.7
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'diff_gaussian_rasterization._C' extension
      creating build/temp.linux-x86_64-cpython-37
      creating build/temp.linux-x86_64-cpython-37/cuda_rasterizer
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/hwg/2_Code/MonoGS/submodules/diff-gaussian-rasterization/setup.py", line 32, in <module>
          'build_ext': BuildExtension
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/ccompiler.py", line 600, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 513, in unix_wrap_single_compile
          cflags = unix_cuda_flags(cflags)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 480, in unix_cuda_flags
          cflags + _get_cuda_arch_flags(cflags))
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1694, in _get_cuda_arch_flags
          arch_list[-1] += '+PTX'
      IndexError: list index out of range
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization
  error: subprocess-exited-with-error
  × Running setup.py install for simple_knn did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.7'
      running install
      /home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      !!
        self.initialize_options()
      running build
      running build_ext
      /home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      /home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.7) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no g++ version bounds defined for CUDA version 11.7
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'simple_knn._C' extension
      creating build
      creating build/temp.linux-x86_64-cpython-37
      gcc -pthread -B /home/hwg/miniconda3/envs/MonoGS/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/include -I/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/include/TH -I/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/hwg/miniconda3/envs/MonoGS/include/python3.7m -c ext.cpp -o build/temp.linux-x86_64-cpython-37/ext.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
      cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/hwg/2_Code/MonoGS/submodules/simple-knn/setup.py", line 33, in <module>
          'build_ext': BuildExtension
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/command/install.py", line 78, in run
          return orig.install.run(self)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/install.py", line 697, in run
          self.run_command('build')
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 555, in build_extension
          depends=ext.depends,
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/setuptools/_distutils/ccompiler.py", line 600, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 513, in unix_wrap_single_compile
          cflags = unix_cuda_flags(cflags)
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 480, in unix_cuda_flags
          cflags + _get_cuda_arch_flags(cflags))
        File "/home/hwg/miniconda3/envs/MonoGS/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1694, in _get_cuda_arch_flags
          arch_list[-1] += '+PTX'
      IndexError: list index out of range
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
 
× Encountered error while trying to install package.
╰─> simple_knn
 
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
 
failed
 
CondaEnvException: Pip failed
```

**Comment by gmberton** [comment]
I had the same issue, you can solve it by cloning the repo with '--recursive' as pointed out [in this other issue](https://github.com/muskie82/MonoGS/issues/8)
